Repository DataGerry/DataGerry, pull requests merged in 2020-10, with the labels that each got.

#60 [NET-548] Bugfix router outlet reloads
  app/angular.json
  app/src/app/app-routing.module.ts
  app/src/app/app.component.html
  app/src/app/app.component.ts
  app/src/app/app.module.ts
  app/src/app/auth/auth.module.ts
  app/src/app/auth/guards/auth.guard.ts
  app/src/app/auth/guards/permission.guard.ts
  app/src/app/auth/interceptors/basic-auth.interceptor.ts
  app/src/app/auth/login.component.ts
  app/src/app/dashboard/dashboard-routing.module.ts
  app/src/app/debug/debug-routing.module.ts
  app/src/app/error/error-message/error-message-container.component.html
  app/src/app/error/error-message/error-message-container.component.scss
  app/src/app/error/error-message/error-message-container.component.ts
  app/src/app/error/error-message/error-message.component.html
  app/src/app/error/error-message/error-message.component.scss
  app/src/app/error/error-message/error-message.component.ts
  app/src/app/error/error-message/error-message.module.ts
  app/src/app/error/error-routing.module.ts
  app/src/app/error/error.module.ts
  app/src/app/error/interceptors/http-error.interceptor.tx.ts
  app/src/app/error/services/error-message.service.ts
  app/src/app/export/export-routing.module.ts
  app/src/app/file-manager/file-manager-routing.module.ts
  app/src/app/framework/framework-routing.module.ts
  app/src/app/framework/object/object-list-by-type/object-list-by-type.component.ts
  app/src/app/framework/object/object-view/object-view.component.ts
  app/src/app/import/import-routing.module.ts
  app/src/app/info/info-routing.module.ts
  app/src/app/layout/layout.module.ts
  app/src/app/layout/structure/loading-screen/loading-screen.component.html
  app/src/app/layout/structure/loading-screen/loading-screen.component.scss
  app/src/app/layout/structure/loading-screen/loading-screen.component.ts
  app/src/app/layout/structure/navigation/navigation.component.html
  app/src/app/layout/structure/navigation/navigation.component.ts
  app/src/app/main/main-routing.module.ts
  app/src/app/main/main.module.ts
  app/src/app/management/management-routing.module.ts
  app/src/app/search/search-routing.module.ts
  app/src/app/settings/docapi-settings/docapi-settings-routing.module.ts
  app/src/app/settings/docapi-settings/docapi-settings.module.ts
  app/src/app/settings/settings-routing.module.ts
  app/src/app/settings/settings.module.ts
Labels: angular, bug

#68 [NET-460] Follow search references
  app/src/app/search/search-result/search-result-bar/search-result-bar.component.html
  app/src/app/search/search-result/search-result-bar/search-result-bar.component.ts
  app/src/app/search/search.component.html
  app/src/app/search/search.component.ts
  cmdb/interface/rest_api/search_routes.py
  cmdb/search/query/builder.py
  cmdb/search/search_result.py
  cmdb/search/searchers.py
Labels: enhancement

#80 [NET-612] No authentication config possible
  cmdb/security/auth/__init__.py
  cmdb/security/auth/providers/internal_providers.py
Labels: bug

#79 [NET-624] Passing parameters in the HTTP packet.
  app/src/app/framework/object/object-bulk-change/object-bulk-change.component.ts
  app/src/app/framework/services/object.service.ts
Labels: bug

#84 [NET-620] create type ref fix
  app/src/app/framework/services/type.service.ts
Labels: bug

#85 [NET-626] Changed routes used to check if the name of a template or j…
  app/src/app/docapi/docapi.service.ts
  app/src/app/settings/services/exportd-job.service.ts
  cmdb/interface/rest_api/docapi_routes.py
  cmdb/interface/rest_api/exporter_routes/exportd_job_routes.py
Labels: bug

#81 [NET-579] LDAP password hidden
  app/src/app/framework/render/fields/text/password.component.html
  app/src/app/framework/render/fields/text/password.component.ts
  cmdb/security/auth/providers/external_providers.py
Labels: bug

#86 [NET-619] fixed json export
  cmdb/interface/rest_api/exporter_routes/export_type_routes.py
Labels: bug

#82 [NET-610] Remove config reload option
  app/src/app/settings/system/properties/properties.component.html
  app/src/app/settings/system/properties/properties.component.ts
  app/src/app/settings/system/server/server.component.html
  app/src/app/settings/system/server/server.component.scss
  app/src/app/settings/system/server/server.component.ts
  app/src/app/settings/system/system-routing.module.ts
  app/src/app/settings/system/system.module.ts
  app/src/app/settings/system/system.service.ts
  cmdb/interface/rest_api/settings_routes/system_routes.py
Labels: bug

#89 [NET-615] Bugfix category editmode get types
  app/src/app/framework/category/category-form/category-form.component.ts
  app/src/app/framework/models/cmdb-category.ts
Labels: bug

#92 [NET-621] Remove wrong header target cell
  app/src/app/framework/type/type.component.ts
Labels: bug

#91 [NET-641] Fix user management insert convertion
  cmdb/__setup__.py
  cmdb/user_management/models/group.py
  cmdb/user_management/models/user.py
Labels: bug

#94 [NET-468] Feature object counter in category sidebar
  app/src/app/framework/object/components/object-actions/object-actions.component.ts
  app/src/app/framework/object/object-add/object-add.component.ts
  app/src/app/framework/object/object-copy/object-copy.component.ts
  app/src/app/framework/object/object-list-by-type/object-list-by-type.component.ts
  app/src/app/layout/components/table/table.component.ts
  app/src/app/layout/services/sidebar.service.ts
  app/src/app/layout/structure/sidebar/sidebar-type.component.ts
Labels: enhancement

#97 [NET-650] Add length validation for ldap connection entries
  cmdb/security/auth/providers/external_providers.py
Labels: bug

#98 Bugfix/net 645 category list at type generator
  app/src/app/framework/category/components/modals/delete-category-modal/delete-category-modal.component.ts
  app/src/app/framework/services/category.service.ts
Labels: bug

#93 [NET-623] Bugfix type cleanup button
  app/src/app/framework/models/cmdb-render.ts
  app/src/app/framework/models/cmdb-type.ts
  app/src/app/framework/services/object.service.ts
  app/src/app/framework/type/builder/builder.module.ts
  app/src/app/framework/type/builder/modals/cleanup-modal/cleanup-modal.component.html
  app/src/app/framework/type/builder/modals/cleanup-modal/cleanup-modal.component.ts
  app/src/app/framework/type/components/clean-button/clean-button.component.html
  app/src/app/framework/type/components/clean-button/clean-button.component.scss
  app/src/app/framework/type/components/clean-button/clean-button.component.ts
  app/src/app/framework/type/modals/cleanup-modal/cleanup-modal.component.html
  app/src/app/framework/type/modals/cleanup-modal/cleanup-modal.component.scss
  app/src/app/framework/type/modals/cleanup-modal/cleanup-modal.component.ts
  app/src/app/framework/type/type.component.html
  app/src/app/framework/type/type.component.ts
  app/src/app/framework/type/type.module.ts
  app/src/app/layout/structure/navigation/navigation.component.html
  cmdb/framework/cmdb_object.py
  cmdb/framework/cmdb_render.py
  cmdb/framework/managers/framework_manager.py
  cmdb/framework/managers/type_manager.py
  cmdb/framework/models/type.py
  cmdb/framework/results/list.py
  cmdb/interface/response.py
  cmdb/interface/rest_api/framework_routes/object_routes.py
  cmdb/interface/rest_api/importer_routes/importer_type_routes.py
  docs/source/api/rest/framework.rst
Labels: bug

#95 [NET-644] Get assigned types for categories.
  app/src/app/framework/category/category-edit/category-edit.component.ts
  app/src/app/framework/category/category-form/category-form.component.html
  app/src/app/framework/category/category-form/category-form.component.ts
  app/src/app/framework/services/type.service.ts
  app/src/app/services/api-call.service.ts
Labels: bug

#96 [NET-647] Search filter adapted for the type list.
  app/src/app/framework/type/type.component.ts
Labels: bug

#99 [NET-637] Bugfix attachment actualisation
  app/src/app/layout/components/file-explorer/fileexplorer.component.ts
  app/src/app/layout/components/file-explorer/service/file.service.ts
  app/src/app/layout/helpers/modals/add-attachments-modal/add-attachments-modal.component.ts
  app/src/app/layout/structure/navigation/navigation.component.html
  cmdb/interface/rest_api/media_library_routes/media_file_route_utils.py
  cmdb/interface/rest_api/media_library_routes/media_file_routes.py
  cmdb/media_library/media_file.py
  cmdb/media_library/media_file_base.py
  cmdb/media_library/media_file_manager.py
  cmdb/media_library/media_file_metadata.py
Labels: bug

#102 [NET-632] fixed reference types not showing
  app/src/app/framework/type/builder/configs/edits/ref-field-edit.component.ts
Labels: bug

#100 [NET-581] Load category tree for sidebar after login.
  app/src/app/framework/category/category-add/category-add.component.ts
  app/src/app/framework/category/category-edit/category-edit.component.ts
  app/src/app/framework/category/category.component.html
  app/src/app/framework/category/category.component.ts
  app/src/app/framework/type/type-builder/type-basic-step/type-basic-step.component.ts
  app/src/app/framework/type/type-builder/type-builder.component.ts
  app/src/app/layout/services/sidebar.service.ts
  app/src/app/layout/structure/sidebar/sidebar.component.ts
Labels: bug
