Repository DataGerry/DataGerry, pull requests merged in 2020-09, with the labels that each got.

#34 [Dependabot] Fix CVE-2020-7720
  app/package-lock.json
  app/package.json
Labels: dependencies

#35 Cleanup
  .dependabot/config.yml
  .github/dependabot.yml
  cmdb/__main__.py
  cmdb/__setup__.py
  cmdb/framework/__init__.py
  cmdb/framework/cmdb_collection.py
  cmdb/framework/cmdb_object_manager.py
  cmdb/framework/cmdb_status.py
  cmdb/interface/cmdb_app.py
  cmdb/interface/rest_api/__init__.py
  cmdb/interface/rest_api/framework_routes/collection_routes.py
  cmdb/interface/rest_api/framework_routes/status_routes.py
  cmdb/interface/rest_api/user_management_routes/user_routes.py
  cmdb/plugins/__init__.py
  cmdb/plugins/auth/__init__.py
  cmdb/plugins/plugin_system.py
  cmdb/security/auth/providers/internal_providers.py
  cmdb/security/security.py
  cmdb/user_management/user_manager.py
  cmdb/utils/data_factory.py
  cmdb/utils/wraps.py
  tests/__init__.py
  tests/codingstandards/__init__.py
  tests/codingstandards/test_licenses.py
  tests/conftest.py
  tests/fixtures/__init__.py
  tests/fixtures/plugins/__init__.py
  tests/fixtures/plugins/example/__init__.py
  tests/fixtures/plugins/example/test_plugin/__init__.py
  tests/fixtures/plugins/example/test_plugin/test.py
  tests/functional/__init__.py
  tests/functional/test_search.py
  tests/pytest_plugins/__init__.py
  tests/pytest_plugins/pytest_config.py
  tests/unit/__init__.py
  tests/unit/test_framework/__init__.py
  tests/unit/test_framework/test_framework_link.py
  tests/unit/test_framework/test_framework_log.py
  tests/unit/test_framework/test_framework_status.py
  tests/unit/test_framework/test_framework_type.py
  tests/unit/test_plugins.py
  tests/unit/test_search/__init__.py
  tests/unit/test_search/test_builder.py
  tests/unit/test_security_keys.py
  tests/unit/test_security_token.py
  tests/unit/test_system_reader.py
Labels: code conventions, dependencies, enhancement

#48 [NET-553][NET-554] Bugfix flask caching unused
  cmdb/interface/rest_api/__init__.py
  cmdb/interface/rest_api/settings_routes/system_routes.py
  requirements.txt
Labels: bug, dependencies

#49 [NET-526] Feature toast module
  app/src/app/app.module.ts
  app/src/app/file-manager/modal/new-folder-dialog/new-folder-dialog.component.ts
  app/src/app/framework/object/components/object-header/object-header.component.ts
  app/src/app/framework/object/components/object-summary/object-summary.component.ts
  app/src/app/framework/object/object-edit/object-edit.component.html
  app/src/app/framework/object/object-edit/object-edit.component.ts
  app/src/app/framework/render/fields/components.fields.ts
  app/src/app/framework/type/type-builder/type-basic-step/type-basic-step.component.ts
  app/src/app/framework/type/type-builder/type-builder.component.ts
  app/src/app/layout/toast/toast-component/toast-component.component.html
  app/src/app/layout/toast/toast-component/toast-component.component.scss
  app/src/app/layout/toast/toast-component/toast-component.component.ts
  app/src/app/layout/toast/toast-container/toast-container.component.html
  app/src/app/layout/toast/toast-container/toast-container.component.scss
  app/src/app/layout/toast/toast-container/toast-container.component.ts
  app/src/app/layout/toast/toast.module.ts
  app/src/app/layout/toast/toast.service.ts
  app/src/app/management/groups/groups-add/groups-add.component.ts
  app/src/app/management/groups/groups-delete/groups-delete.component.ts
  app/src/app/management/groups/groups-edit/groups-edit.component.ts
  app/src/app/management/users/modals/users-passwd-modal/users-passwd-modal.component.ts
  app/src/app/management/users/user-view/user-view.component.ts
  app/src/app/management/users/users-add/users-add.component.ts
  app/src/app/management/users/users-delete/users-delete.component.ts
  app/src/app/management/users/users-edit/users-edit.component.ts
  app/src/app/search/search-result/search-result-bar/search-result-bar.component.ts
  app/src/app/settings/auth-settings/auth-settings.component.ts
  app/src/app/settings/docapi-settings/docapi-settings-builder/docapi-settings-builder.component.ts
  app/src/app/settings/exportd-job-settings/exportd-job-logs/exportd-job-logs.component.ts
  app/src/app/settings/exportd-job-settings/exportd-job-settings-builder/exportd-job-settings-builder.component.ts
  app/src/app/settings/exportd-job-settings/exportd-job-settings-list/exportd-job-settings-list.component.ts
  app/src/app/settings/log-settings/log-exportd-settings/log-exportd-settings.component.ts
  app/src/app/settings/log-settings/log-object-settings/log-object-settings.component.ts
  app/src/app/settings/system/properties/properties.component.ts
  app/src/scss/_toast.scss
Labels: angular, enhancement

#47 [NET-550][NET-551] Update gunicorn to 20.0.4
  requirements.txt
Labels: bug, dependencies

#50 [NET-559] Cleanup python packages
  cmdb/__main__.py
  cmdb/utils/termcolor.py
  requirements.txt
Labels: dependencies, enhancement

#52 [NET-551] Fix gunicorn logging output to stdout and stderr
  cmdb/interface/config.py
  cmdb/interface/docs/__init__.py
  cmdb/interface/gunicorn.py
  cmdb/interface/net_app/__init__.py
  cmdb/interface/rest_api/__init__.py
  cmdb/utils/logger.py
Labels: bug

#51 [NET-565] Bugfix inconsistency manager usage
  cmdb/framework/managers/__init__.py
  cmdb/framework/managers/category_manager.py
  cmdb/framework/managers/error/__init__.py
  cmdb/framework/managers/error/framework_errors.py
  cmdb/framework/managers/framework_manager.py
  cmdb/framework/managers/type_manager.py
  cmdb/interface/rest_api/framework_routes/category_routes.py
  cmdb/interface/rest_api/framework_routes/type_routes.py
  cmdb/manager/__init__.py
  cmdb/manager/errors.py
Labels: bug, code conventions, enhancement

#53 [NET-571] Missing type table functions
  app/src/app/framework/type/type.component.html
  app/src/app/framework/type/type.component.ts
Labels: enhancement
