Repository DataGerry/DataGerry, pull requests merged in 2020-12, with the labels that each got.

#143 [NET-690] Hide Types in sidebar/dropdowns if user has no acl permissions
  app/src/app/auth/services/acl-permission.service.ts
  app/src/app/framework/category/category-form/category-form.component.html
  app/src/app/framework/category/category-form/category-form.component.ts
  app/src/app/framework/services/type.service.ts
  app/src/app/layout/structure/sidebar/sidebar-category.component.html
  app/src/app/layout/structure/sidebar/sidebar-category.component.ts
  app/src/app/layout/structure/sidebar/sidebar.component.html
  cmdb/interface/rest_api/framework_routes/category_routes.py
Labels: enhancement

#150 [NET-685] acls for object files exports
  app/src/app/export/export-objects/export-objects.component.html
  app/src/app/export/export-objects/export-objects.component.ts
  app/src/app/export/export-objects/model/export-objects-file-extension.ts
  app/src/app/export/export.service.ts
  app/src/app/framework/object/components/object-table-head/object-table-head.component.html
  app/src/app/framework/object/components/object-table-head/object-table-head.component.ts
  app/src/app/framework/object/object-view/object-footer/object-reference-list/object-reference-list.component.html
  app/src/app/framework/object/object-view/object-footer/object-reference-list/object-reference-list.component.ts
  app/src/app/framework/object/objects-by-type/objects-by-type.component.ts
  cmdb/file_export/export_types.py
  cmdb/file_export/file_exporter.py
  cmdb/interface/rest_api/exporter_routes/file_routes.py
Labels: enhancement

#151 [NET-684] Handle object reference acl
  app/src/app/app.module.ts
  app/src/app/framework/object/object-view/object-view.component.html
  app/src/app/framework/render/fields/special/ref.component.html
  app/src/app/framework/render/fields/special/ref.component.ts
  app/src/app/framework/render/render-element/render-element.component.html
  app/src/app/framework/render/render-element/render-element.component.ts
  app/src/app/framework/render/simple/special/ref-simple.component.html
  app/src/app/framework/render/simple/special/ref-simple.component.ts
  cmdb/framework/cmdb_object_manager.py
  cmdb/framework/cmdb_render.py
  cmdb/interface/rest_api/framework_routes/object_routes.py
Labels: enhancement

#155 [NET-763] Implement email validation on user feedback form
  app/src/app/layout/components/feedback-form/feedback-form.component.html
  app/src/app/layout/components/feedback-form/feedback-form.component.ts
Labels: bug

#152 [NET-739] Angular loading indicators
  app/package-lock.json
  app/package.json
  app/src/app/app.component.html
  app/src/app/app.component.ts
  app/src/app/app.module.ts
  app/src/app/framework/category/components/modals/add-category-modal/add-category-modal.component.ts
  app/src/app/framework/object/object.module.ts
  app/src/app/import/import-objects/import-objects.component.ts
  app/src/app/layout/layout.module.ts
  app/src/app/layout/progress/progress-bar.service.ts
  app/src/app/layout/progress/progress-bar/progress-bar.component.html
  app/src/app/layout/progress/progress-bar/progress-bar.component.scss
  app/src/app/layout/progress/progress-bar/progress-bar.component.ts
  app/src/app/layout/progress/progress-bar/progress-bar.types.ts
  app/src/app/layout/progress/progress-spinner.service.ts
  app/src/app/layout/progress/progress-spinner/progress-spinner.component.html
  app/src/app/layout/progress/progress-spinner/progress-spinner.component.scss
  app/src/app/layout/progress/progress-spinner/progress-spinner.component.ts
  app/src/app/layout/progress/progress-spinner/progress-spinner.types.ts
  app/src/app/layout/progress/progress.module.ts
  app/src/app/search/search.component.ts
  app/src/app/search/search.module.ts
  app/src/app/services/app-loading.service.ts
  app/src/app/settings/auth-settings/auth-settings.component.ts
Labels: angular, enhancement

#153 [NET-761] remove expression to ignore all white space characters.
  app/src/app/framework/services/type.service.ts
Labels: bug

#156 [NET-757] Add delete action logic to dashboard table.
  app/src/app/dashboard/dashboard.component.html
  app/src/app/dashboard/dashboard.component.ts
Labels: bug

#157 [NET-758] Added new conditions for protected references.
  app/src/app/framework/render/fields/special/ref.component.ts
Labels: bug

#158 [NET-688] Backend: Check linked objects for acls.
  cmdb/framework/cmdb_object_manager.py
  cmdb/interface/rest_api/framework_routes/object_link_routes.py
Labels: bug

#161 [NET-800] Get categories for type chart with new API.
  app/src/app/dashboard/dashboard.component.ts
Labels: bug

#164 [NET-800] Implement missing OnDestroy.
  app/src/app/dashboard/dashboard.component.ts
Labels: bug

#160 [NET-765] Refactor database module
  cmdb/__main__.py
  cmdb/__setup__.py
  cmdb/__update__.py
  cmdb/data_storage/database_connection.py
  cmdb/database/__init__.py
  cmdb/database/connection.py
  cmdb/database/counter.py
  cmdb/database/errors/__init__.py
  cmdb/database/errors/connection_errors.py
  cmdb/database/errors/database_errors.py
  cmdb/database/managers.py
  cmdb/database/utils.py
  cmdb/docapi/docapi_template/docapi_template_base.py
  cmdb/docapi/docapi_template/docapi_template_manager.py
  cmdb/exportd/exportd_job/exportd_job_base.py
  cmdb/exportd/exportd_job/exportd_job_manager.py
  cmdb/exportd/exporter_base.py
  cmdb/exportd/service.py
  cmdb/file_export/export_types.py
  cmdb/file_export/file_exporter.py
  cmdb/framework/cmdb_base.py
  cmdb/framework/cmdb_object_manager.py
  cmdb/framework/cmdb_render.py
  cmdb/framework/managers/category_manager.py
  cmdb/framework/managers/framework_manager.py
  cmdb/framework/managers/object_manager.py
  cmdb/framework/managers/type_manager.py
  cmdb/importer/importer_base.py
  cmdb/interface/cmdb_app.py
  cmdb/interface/docs/__init__.py
  cmdb/interface/net_app/__init__.py
  cmdb/interface/rest_api/__init__.py
  cmdb/interface/rest_api/connection.py
  cmdb/interface/rest_api/debug_routes.py
  cmdb/interface/rest_api/framework_routes/object_routes.py
  cmdb/interface/rest_api/importer_routes/importer_object_routes.py
  cmdb/manager/__init__.py
  cmdb/media_library/media_file_manager.py
  cmdb/security/auth/providers/external_providers.py
  cmdb/security/auth/providers/internal_providers.py
  cmdb/security/key/generator.py
  cmdb/security/key/holder.py
  cmdb/security/security.py
  cmdb/security/token/generator.py
  cmdb/updater/updater.py
  cmdb/user_management/managers/account_manager.py
  cmdb/user_management/managers/group_manager.py
  cmdb/user_management/managers/setting_manager.py
  cmdb/user_management/managers/user_manager.py
  cmdb/user_management/models/group.py
  cmdb/user_management/models/settings.py
  cmdb/user_management/user_manager.py
  cmdb/utils/system_reader.py
  cmdb/utils/system_writer.py
  requirements.txt
Labels: refactor

#166 [NET-688] Enforce object links acl
  app/src/app/error/interceptors/http-error.interceptor.tx.ts
  app/src/app/framework/object/modals/object-link-add-modal/object-link-add-modal.component.html
  app/src/app/framework/object/modals/object-link-add-modal/object-link-add-modal.component.ts
  app/src/app/framework/object/object-view/object-footer/object-links/object-links.component.html
  app/src/app/framework/object/object-view/object-footer/object-links/object-links.component.ts
  app/src/app/framework/services/link.service.ts
  app/src/app/framework/services/object.service.ts
  cmdb/framework/cmdb_link.py
  cmdb/framework/cmdb_object_manager.py
  cmdb/interface/rest_api/framework_routes/object_link_routes.py
Labels: enhancement

#174 [NET-656] Last object editor
  app/src/app/dashboard/dashboard.component.ts
  app/src/app/framework/models/cmdb-object.ts
  app/src/app/framework/models/cmdb-render.ts
  cmdb/framework/cmdb_object.py
  cmdb/framework/cmdb_object_manager.py
  cmdb/framework/cmdb_render.py
Labels: enhancement

#171 [NET-766] Category datatables replacement
  app/src/app/framework/category/category.component.html
  app/src/app/framework/category/category.component.ts
  app/src/app/framework/category/category.module.ts
  app/src/app/framework/category/components/category-node/category-node.component.ts
  app/src/app/framework/category/components/modals/delete-category-modal/delete-category-modal.component.ts
Labels: enhancement

#176 [NET-801] Added acls for dashboard charts.
  app/src/app/dashboard/dashboard.component.ts
  app/src/app/framework/services/type.service.ts
  cmdb/framework/cmdb_object_manager.py
  cmdb/interface/rest_api/framework_routes/object_routes.py
Labels: enhancement

#178 [NET-820] Implement some missing ui toasts
  app/src/app/framework/object/components/object-actions/object-actions.component.ts
  app/src/app/framework/object/object-add/object-add.component.ts
  app/src/app/framework/object/object-copy/object-copy.component.ts
  app/src/app/framework/type/type-builder/type-builder.component.ts
  app/src/app/framework/type/type-delete/type-delete.component.ts
Labels: enhancement
