Repository DataGerry/DataGerry, pull requests merged in 2020-11, with the labels that each got.

#103 [NET-631] Display number of search results(active/inactive).
  app/src/app/search/models/search-result.ts
  app/src/app/search/search-bar/search-bar.component.html
  app/src/app/search/search-bar/search-bar.component.ts
  app/src/app/search/search.service.ts
  cmdb/interface/rest_api/search_routes.py
Labels: enhancement

#104 [NET-659] Export selected objects. Checks if zipping-parameter is tru…
  app/src/app/export/export.service.ts
  cmdb/interface/rest_api/exporter_routes/file_routes.py
Labels: bug

#105 [NET-657] Import Object as JSON. Improve methods declared in a static…
  cmdb/importer/importer_object.py
  cmdb/importer/improve_object.py
Labels: bug

#108 [NET-651] Make regex in search optional.
  app/src/app/framework/services/category.service.ts
  app/src/app/framework/services/type.service.ts
  app/src/app/search/search-bar/search-bar-tag/search-bar-tag-icon.component.html
  app/src/app/search/search-bar/search-bar.component.html
  app/src/app/search/search-bar/search-bar.component.ts
  app/src/app/search/search-result/search-result-bar/search-result-bar.component.ts
  app/src/app/services/validator.service.ts
  cmdb/search/params.py
  cmdb/search/query/pipe_builder.py
Labels: enhancement

#116 [NET-675] Remove cache debug message
  app/src/app/services/request-cache.service.ts
Labels: bug

#115 [NET-672] routeReuseStrategy replaced by resolve.
  app/src/app/framework/object/object-routing.module.ts
  app/src/app/framework/object/object-view/object-view.component.html
  app/src/app/framework/object/object-view/object-view.component.ts
  app/src/app/framework/object/objects-by-type/objects-by-type.component.ts
  app/src/app/framework/resolvers/object-view-resolver.service.ts
  app/src/app/framework/services/object.service.ts
Labels: bug

#118 [NET-676] Implement dashboard tables with new table module
  app/angular.json
  app/src/app/dashboard/dashboard.component.html
  app/src/app/dashboard/dashboard.component.ts
  app/src/app/dashboard/dashboard.module.ts
  app/src/app/dashboard/latest-changes-view/latest-changes-view.component.html
  app/src/app/dashboard/latest-changes-view/latest-changes-view.component.scss
  app/src/app/dashboard/latest-changes-view/latest-changes-view.component.ts
  app/src/app/dashboard/newest-view/newest-view.component.html
  app/src/app/dashboard/newest-view/newest-view.component.scss
  app/src/app/dashboard/newest-view/newest-view.component.ts
  app/src/app/framework/object/object.module.ts
  cmdb/interface/rest_api/framework_routes/object_routes.py
Labels: bug, enhancement

#117 [NET-663] Feature storing table config
  app/src/app/auth/services/auth.service.ts
  app/src/app/framework/object/object-routing.module.ts
  app/src/app/framework/object/objects-by-type/objects-by-type.component.html
  app/src/app/framework/object/objects-by-type/objects-by-type.component.ts
  app/src/app/layout/table/components/table-config-switch/table-config-switch.component.ts
  app/src/app/layout/table/components/table-states/table-state.component.html
  app/src/app/layout/table/components/table-states/table-state.component.scss
  app/src/app/layout/table/components/table-states/table-state.component.ts
  app/src/app/layout/table/table.component.html
  app/src/app/layout/table/table.component.ts
  app/src/app/layout/table/table.module.ts
  app/src/app/layout/table/table.service.ts
  app/src/app/layout/table/table.types.ts
  app/src/app/main/main.module.ts
  app/src/app/management/user-settings/resolvers/user-settings-resolver.service.ts
  app/src/app/management/user-settings/services/user-settings-db.service.ts
  app/src/app/management/user-settings/services/user-settings.service.ts
Labels: enhancement

#121 [NET-671] Add column visibility reset
  app/src/app/framework/object/objects-by-type/objects-by-type.component.html
  app/src/app/framework/object/objects-by-type/objects-by-type.component.ts
  app/src/app/layout/table/components/table-states/table-state.component.ts
  app/src/app/layout/table/table.component.ts
Labels: bug, duplicate, enhancement

#120 [NET-677] Automatic field mapping in CSV importer.
  app/src/app/import/import-objects/import-objects.component.ts
  app/src/app/import/import-objects/type-mapping/type-mapping.component.ts
Labels: bug

#127 [NET-704] Fix auto setting of url parameters to search bar entries
  app/src/app/search/search-bar/search-bar.component.ts
Labels: bug

#128 [NET-706] Bugfix date display error
  app/src/app/framework/object/objects-by-type/objects-by-type.component.html
  app/src/app/framework/object/objects-by-type/objects-by-type.component.ts
  cmdb/__setup__.py
  cmdb/interface/response.py
  cmdb/interface/rest_api/user_management_routes/user_routes.py
  cmdb/interface/route_utils.py
  cmdb/security/auth/providers/external_providers.py
  cmdb/user_management/models/user.py
Labels: bug

#129 [NET-711] Removed error-output from frontend console.
  app/src/app/layout/components/file-explorer/service/file.service.ts
  cmdb/interface/rest_api/media_library_routes/media_file_routes.py
Labels: bug

#131 [NET-714] Add validation parser on user
  cmdb/user_management/models/user.py
  requirements.txt
Labels: bug

#132 [NET-715] Fix selected category id compare in type builder
  app/src/app/framework/type/type-builder/type-builder.component.ts
Labels: angular, bug

#134 [NET-716] Fix category update error on type builder
  app/src/app/framework/type/type-builder/type-builder.component.ts
Labels: bug

#133 [NET-681] Change type model for new object ACLs
  app/src/app/acl/acl.module.ts
  app/src/app/acl/acl.types.ts
  app/src/app/framework/models/cmdb-type.ts
  app/src/app/framework/type/type-builder/type-acl-step/groups-acl-tabs/groups-acl-tabs.component.html
  app/src/app/framework/type/type-builder/type-acl-step/groups-acl-tabs/groups-acl-tabs.component.scss
  app/src/app/framework/type/type-builder/type-acl-step/groups-acl-tabs/groups-acl-tabs.component.ts
  app/src/app/framework/type/type-builder/type-acl-step/type-acl-step.component.html
  app/src/app/framework/type/type-builder/type-acl-step/type-acl-step.component.scss
  app/src/app/framework/type/type-builder/type-acl-step/type-acl-step.component.ts
  app/src/app/framework/type/type-builder/type-builder.component.html
  app/src/app/framework/type/type-builder/type-builder.component.ts
  app/src/app/framework/type/type.module.ts
  app/src/app/layout/components/block/block.component.html
  app/src/app/layout/components/block/block.component.scss
  app/src/app/layout/components/block/block.component.ts
  app/src/app/layout/layout.module.ts
  cmdb/framework/models/type.py
  cmdb/security/access_control/__init__.py
Labels: enhancement

#137 [NET-682] Enforce acl object crud
  app/src/app/framework/services/object.service.ts
  cmdb/framework/cmdb_object_manager.py
  cmdb/framework/managers/category_manager.py
  cmdb/framework/managers/framework_manager.py
  cmdb/framework/managers/object_manager.py
  cmdb/framework/models/type.py
  cmdb/interface/rest_api/framework_routes/object_routes.py
  cmdb/interface/route_utils.py
  cmdb/search/query/builder.py
  cmdb/search/query/pipe_builder.py
  cmdb/search/searchers.py
  cmdb/security/acl/__init__.py
  cmdb/security/acl/builder.py
  cmdb/security/acl/control.py
  cmdb/security/acl/errors.py
  cmdb/security/acl/permission.py
  cmdb/security/acl/sections.py
Labels: enhancement

#138 [NET-728] Remove/Update formcontrols if already exist.
  app/src/app/framework/render/render-element/render-element.component.ts
Labels: bug

#142 [NET-712] Bugfix bulk preview show references
  app/src/app/framework/object/object-bulk-change/object-bulk-change-editor/object-bulk-change-editor.component.html
  app/src/app/framework/object/object-bulk-change/object-bulk-change-editor/object-bulk-change-editor.component.ts
  app/src/app/framework/object/object-bulk-change/object-bulk-change-preview/object-bulk-change-preview.component.html
  app/src/app/framework/object/object-bulk-change/object-bulk-change-preview/object-bulk-change-preview.component.ts
  app/src/app/framework/object/object-bulk-change/object-bulk-change.component.html
  app/src/app/framework/object/object-bulk-change/object-bulk-change.component.ts
  app/src/app/framework/object/objects-by-type/objects-by-type.component.html
  app/src/app/framework/object/objects-by-type/objects-by-type.component.ts
  app/src/app/framework/render/components/object-bulk-input-appends/object-bulk-input-appends.component.html
  app/src/app/framework/render/components/object-bulk-input-appends/object-bulk-input-appends.component.ts
  app/src/app/framework/render/fields/choice/checkbox.component.html
  app/src/app/framework/render/fields/choice/radio.component.html
  app/src/app/framework/render/fields/choice/select.component.html
  app/src/app/framework/render/fields/components.fields.ts
  app/src/app/framework/render/fields/date/date.component.html
  app/src/app/framework/render/fields/math/number.component.html
  app/src/app/framework/render/fields/special/ref.component.html
  app/src/app/framework/render/fields/special/ref.component.ts
  app/src/app/framework/render/fields/text/password.component.html
  app/src/app/framework/render/fields/text/text.component.html
  app/src/app/framework/render/fields/textarea/textarea.component.html
  app/src/app/framework/render/render-element/render-element.component.ts
  app/src/app/framework/render/render.component.html
  app/src/app/framework/render/render.component.ts
  app/src/app/framework/render/simple/special/ref-simple.component.html
  app/src/app/framework/render/simple/special/ref-simple.component.ts
  cmdb/interface/rest_api/framework_routes/object_routes.py
Labels: bug

#140 [NET-689] Restrict Button Access
  app/src/app/auth/directives/permission-link.directive.ts
  app/src/app/auth/services/acl-permission.service.ts
  app/src/app/dashboard/dashboard.component.html
  app/src/app/framework/models/cmdb-render.ts
  app/src/app/framework/object/components/object-actions/object-actions.component.html
  app/src/app/framework/object/components/object-actions/object-actions.component.ts
  app/src/app/framework/object/components/object-table-actions/object-table-actions.component.html
  app/src/app/framework/object/components/object-table-actions/object-table-actions.component.ts
  app/src/app/framework/object/components/object-table-head/object-table-head.component.html
  app/src/app/framework/object/components/object-table-head/object-table-head.component.scss
  app/src/app/framework/object/components/object-table-head/object-table-head.component.ts
  app/src/app/framework/object/object-view/object-view.component.html
  app/src/app/framework/object/object-view/object-view.component.ts
  app/src/app/framework/object/object.module.ts
  app/src/app/framework/object/objects-by-type/objects-by-type.component.html
  cmdb/framework/cmdb_render.py
Labels: enhancement

#147 [NET-683] Search results based on acls
  cmdb/interface/rest_api/search_routes.py
  cmdb/search/searchers.py
Labels: enhancement

#146 [NET-750] Object type selection update
  app/src/app/framework/object/components/object-table-head/object-table-head.component.html
  app/src/app/framework/object/components/object-table-head/object-table-head.component.ts
  app/src/app/framework/object/objects-by-type/objects-by-type.component.html
  app/src/app/framework/object/objects-by-type/objects-by-type.component.ts
Labels: bug

#144 [NET-749] Add ACLs to special routes
  cmdb/interface/rest_api/framework_routes/object_routes.py
Labels: enhancement
