Repository DataGerry/DataGerry, pull requests merged in 2021-03, with the labels that each got.

#259 [NET-909] Dynamic reference summary functionality
  app/src/app/framework/models/cmdb-type-reference.ts
  app/src/app/framework/render/fields/special/ref.component.html
  app/src/app/framework/render/fields/special/ref.component.ts
  app/src/app/framework/render/simple/special/ref-simple.component.html
  app/src/app/framework/render/simple/special/ref-simple.component.ts
  app/src/app/framework/type/builder/builder.module.ts
  app/src/app/framework/type/builder/configs/edits/ref-field-edit.component.html
  app/src/app/framework/type/builder/configs/edits/ref-field-edit.component.ts
  app/src/app/framework/type/builder/controls/controls.common.ts
  cmdb/framework/cmdb_errors.py
  cmdb/framework/cmdb_render.py
  cmdb/framework/models/type.py
Labels: enhancement

#260 [NET-923] Store user settings for all tables
  app/src/app/framework/category/category-routing.module.ts
  app/src/app/framework/category/category.component.html
  app/src/app/framework/category/category.component.ts
  app/src/app/framework/object/components/object-references/object-references-by-type/object-references-by-type.component.html
  app/src/app/framework/object/components/object-references/object-references-by-type/object-references-by-type.component.ts
  app/src/app/framework/object/components/object-references/object-references-table/object-references-table.component.html
  app/src/app/framework/object/components/object-references/object-references-table/object-references-table.component.ts
  app/src/app/framework/object/components/object-references/object-references.component.html
  app/src/app/framework/object/object-routing.module.ts
  app/src/app/framework/type/type-routing.module.ts
  app/src/app/framework/type/type.component.html
  app/src/app/framework/type/type.component.ts
  app/src/app/management/groups/groups-routing.module.ts
  app/src/app/management/groups/groups.component.html
  app/src/app/management/groups/groups.component.ts
  app/src/app/management/management-routing.module.ts
  app/src/app/management/users/users.component.html
  app/src/app/management/users/users.component.ts
  app/src/app/settings/exportd-job-settings/exportd-job-settings-list/exportd-job-settings-list.component.html
  app/src/app/settings/exportd-job-settings/exportd-job-settings-list/exportd-job-settings-list.component.ts
  app/src/app/settings/exportd-job-settings/exportd-job-settings-routing.module.ts
  app/src/app/settings/log-settings/log-exportd-settings/activate-exportd-tab/activate-exportd-tab.component.ts
  app/src/app/settings/log-settings/log-exportd-settings/components/log-exportd-table/log-exportd-table.component.html
  app/src/app/settings/log-settings/log-exportd-settings/components/log-exportd-table/log-exportd-table.component.ts
  app/src/app/settings/log-settings/log-exportd-settings/deactivate-exportd-tab/deleted-exportd-tab.component.ts
  app/src/app/settings/log-settings/log-object-settings/activate-tab/activate-tab.component.html
  app/src/app/settings/log-settings/log-object-settings/activate-tab/activate-tab.component.ts
  app/src/app/settings/log-settings/log-object-settings/deactivate-tab/deactivate-tab.component.html
  app/src/app/settings/log-settings/log-object-settings/deactivate-tab/deactivate-tab.component.ts
  app/src/app/settings/log-settings/log-object-settings/delete-tab/delete-tab.component.html
  app/src/app/settings/log-settings/log-object-settings/delete-tab/delete-tab.component.ts
  app/src/app/settings/log-settings/log-settings-routing.module.ts
Labels: enhancement

#262 [NET-909] Fix summarie label with refID.
  app/src/app/framework/render/fields/special/ref.component.html
  app/src/app/framework/render/simple/special/ref-simple.component.html
  app/src/app/framework/type/builder/configs/edits/ref-field-edit.component.html
Labels: bug

#265 [NET-894] Session timeout notification
  app/src/app/app.module.ts
  app/src/app/auth/auth.module.ts
  app/src/app/auth/guards/auth.guard.ts
  app/src/app/auth/modals/session-timeout-notification-modal/session-timeout-notification-modal.component.html
  app/src/app/auth/modals/session-timeout-notification-modal/session-timeout-notification-modal.component.scss
  app/src/app/auth/modals/session-timeout-notification-modal/session-timeout-notification-modal.component.ts
  app/src/app/auth/services/auth.service.ts
  app/src/app/auth/services/session-timeout.service.ts
  app/src/app/error/interceptors/http-error.interceptor.tx.ts
  app/src/app/layout/structure/footer/footer.component.html
  app/src/app/layout/structure/footer/footer.component.ts
  app/src/app/layout/structure/navigation/navigation.component.ts
  app/src/app/main/main.module.ts
Labels: angular, enhancement

#266 [NET-902] Results display length
  app/src/app/layout/table/table.module.ts
  app/src/app/search/search-result/search-result.component.html
  app/src/app/search/search.component.html
  app/src/app/search/search.component.ts
  app/src/app/search/search.module.ts
Labels: enhancement

#267 [NET-958] Add database manager to tokengenerator in auth_routes
  cmdb/interface/rest_api/auth_routes.py
Labels: bug

#268 [NET-895] Last search page
  app/src/app/search/search.component.html
  app/src/app/search/search.component.ts
Labels: enhancement

#269 [NET-825] Deactivation of types.
  app/src/app/dashboard/dashboard.component.ts
  app/src/app/framework/object/components/object-actions/object-actions.component.html
  app/src/app/framework/object/components/object-table-actions/object-table-actions.component.html
  app/src/app/framework/object/components/object-table-head/object-table-head.component.html
  app/src/app/framework/object/object-add/object-add.component.ts
  app/src/app/framework/services/type.service.ts
  app/src/app/framework/type/type.component.ts
  app/src/app/layout/structure/sidebar/sidebar.component.ts
  cmdb/framework/cmdb_object_manager.py
  cmdb/framework/managers/object_manager.py
  cmdb/interface/rest_api/framework_routes/object_routes.py
  cmdb/interface/rest_api/framework_routes/type_routes.py
  cmdb/interface/rest_api/importer_routes/importer_object_routes.py
  cmdb/security/acl/errors.py
Labels: enhancement

#271 [NET-968] Fix type default native parameter error
  app/src/app/framework/services/type.service.ts
  cmdb/interface/rest_api/framework_routes/type_parameters.py
  cmdb/interface/rest_api/framework_routes/type_routes.py
Labels: bug

#272 Update pillow package to 8.1.2
  requirements.txt
Labels: dependencies

#278 [NET-971] Selecting different radio fields.
  app/src/app/framework/render/fields/choice/radio.component.html
Labels: bug

#281 [NET-966] Default value is checked for undefined. NULL is set instead…
  app/src/app/framework/render/components/input-appends/input-appends.component.ts
Labels: bug

#279 [NET-973] Only check values of type 'checkbox' for boolean
  cmdb/importer/importer_object.py
Labels: bug

#280 [NET-972] Export JSON containing passed data.
  app/src/app/framework/object/components/object-table-head/object-table-head.component.html
  cmdb/exporter/exporter_base.py
Labels: bug

#282 Redesigning the navigation bar.
  app/src/app/export/export.component.html
  app/src/app/export/export.component.ts
  app/src/app/export/export.module.ts
  app/src/app/import/import.component.html
  app/src/app/import/import.component.ts
  app/src/app/import/import.module.ts
  app/src/app/layout/components/feedback-form/feedback-form.component.html
  app/src/app/layout/helpers/modals/feedback-modal/feedback-modal.component.html
  app/src/app/layout/helpers/modals/feedback-modal/feedback-modal.component.scss
  app/src/app/layout/helpers/modals/feedback-modal/feedback-modal.component.ts
  app/src/app/layout/layout.module.ts
  app/src/app/layout/structure/navigation/navigation.component.html
  app/src/app/layout/structure/navigation/navigation.component.scss
  app/src/app/layout/structure/navigation/navigation.component.ts
Labels: refactor

#277 [NET-422] Globally date format
  app/angular.json
  app/package-lock.json
  app/package.json
  app/src/app/app.module.ts
  app/src/app/dashboard/dashboard.component.html
  app/src/app/dashboard/dashboard.component.ts
  app/src/app/framework/object/components/object-log-list/object-log-change-view/object-log-change-view.component.html
  app/src/app/framework/object/components/object-log-list/object-log-change-view/object-log-change-view.component.ts
  app/src/app/framework/object/components/object-log-list/object-log-list.component.html
  app/src/app/framework/object/components/object-log-list/object-log-list.component.ts
  app/src/app/framework/object/object-log/object-log.component.html
  app/src/app/framework/object/objects-by-type/objects-by-type.component.html
  app/src/app/framework/object/objects-by-type/objects-by-type.component.ts
  app/src/app/framework/render/components/input-appends/input-appends.component.html
  app/src/app/framework/render/fields/date/date.component.html
  app/src/app/framework/render/fields/date/date.component.ts
  app/src/app/framework/render/render.component.ts
  app/src/app/framework/render/render.module.ts
  app/src/app/framework/render/simple/date/date-simple.component.html
  app/src/app/framework/render/simple/date/date-simple.component.ts
  app/src/app/framework/type/builder/configs/edits/date-field-edit.component.html
  app/src/app/framework/type/builder/configs/edits/date-field-edit.component.ts
  app/src/app/framework/type/type.component.html
  app/src/app/framework/type/type.component.ts
  app/src/app/layout/components/file-explorer/components/file-view-list/file-view-list.component.html
  app/src/app/layout/pipes/date-formatter.pipe.ts
  app/src/app/layout/structure/navigation/navigation.component.html
  app/src/app/main/main.module.ts
  app/src/app/management/users/users.component.html
  app/src/app/management/users/users.component.ts
  app/src/app/management/users/users.module.ts
  app/src/app/settings/date-settings/date-settings-formatter.service.ts
  app/src/app/settings/date-settings/date-settings.component.html
  app/src/app/settings/date-settings/date-settings.component.scss
  app/src/app/settings/date-settings/date-settings.component.ts
  app/src/app/settings/exportd-job-settings/exportd-job-settings-list/exportd-job-settings-list.component.html
  app/src/app/settings/exportd-job-settings/exportd-job-settings.module.ts
  app/src/app/settings/log-settings/log-exportd-settings/components/log-exportd-table/log-exportd-table.component.html
  app/src/app/settings/log-settings/log-object-settings/activate-tab/activate-tab.component.html
  app/src/app/settings/log-settings/log-object-settings/activate-tab/activate-tab.component.ts
  app/src/app/settings/log-settings/log-object-settings/deactivate-tab/deactivate-tab.component.html
  app/src/app/settings/log-settings/log-object-settings/deactivate-tab/deactivate-tab.component.ts
  app/src/app/settings/log-settings/log-object-settings/delete-tab/delete-tab.component.html
  app/src/app/settings/log-settings/log-object-settings/delete-tab/delete-tab.component.ts
  app/src/app/settings/log-settings/log-settings.module.ts
  app/src/app/settings/services/date-settings.service.ts
  app/src/app/settings/settings-routing.module.ts
  app/src/app/settings/settings.module.ts
  cmdb/framework/managers/type_manager.py
  cmdb/interface/rest_api/__init__.py
  cmdb/interface/rest_api/settings_routes/date_routes.py
  cmdb/settings/__init__.py
  cmdb/settings/date/__init__.py
  cmdb/settings/date/date_settings.py
  cmdb/utils/json_encoding.py
Labels: enhancement

#285 [NET-975] Strict mode Removed. Checked if dateformatter parameter is a date string
  app/src/app/layout/pipes/date-formatter.pipe.ts
Labels: bug

#288 [NET-977] Search line set right-justified
  app/src/app/layout/structure/navigation/navigation.component.html
Labels: bug
