Repository DataGerry/DataGerry, pull requests merged in 2021-02, with the labels that each got.

#220 [NET-873] Objects wont load
  app/src/app/framework/category/category.component.ts
  app/src/app/framework/object/objects-by-type/objects-by-type.component.html
  app/src/app/framework/services/category.service.ts
  app/src/app/framework/type/type-builder/type-basic-step/type-basic-step.component.ts
Labels: bug

#223 [NET-874] Http backend calls breaks
  app/src/app/dashboard/dashboard.component.ts
  app/src/app/framework/category/category-form/category-form.component.html
  app/src/app/framework/category/category-form/category-form.component.ts
  app/src/app/framework/category/components/modals/add-category-modal/add-category-modal.component.ts
  app/src/app/framework/object/object-add/object-add.component.ts
  app/src/app/framework/services/category.service.ts
  app/src/app/framework/services/collection.service.ts
  app/src/app/framework/services/object.service.ts
  app/src/app/framework/services/type.service.ts
  app/src/app/framework/type/type-builder/type-basic-step/type-basic-step.component.ts
  cmdb/database/managers.py
  cmdb/framework/managers/category_manager.py
  cmdb/framework/models/category.py
  cmdb/framework/models/type.py
Labels: bug

#224 [NET-878] Extend Makefile for exporter.
  Makefile
Labels: bug

#225 [NET-879] Fix dashboard services to generic api call
  app/src/app/dashboard/dashboard.component.html
  app/src/app/dashboard/dashboard.component.ts
  app/src/app/framework/object/objects-by-type/objects-by-type.component.ts
  app/src/app/framework/render/fields/special/ref.component.ts
  app/src/app/framework/services/object.service.ts
  app/src/app/framework/services/special.service.ts
Labels: angular, bug

#226 [NET-880] Loading wont disappear
  app/src/app/framework/category/components/modals/add-category-modal/add-category-modal.component.ts
  app/src/app/framework/type/type-builder/type-basic-step/type-basic-step.component.ts
  cmdb/framework/models/type.py
Labels: angular, bug

#228 [NET-881] Move table date pipe in object tables
  app/src/app/dashboard/dashboard.component.ts
  app/src/app/framework/object/objects-by-type/objects-by-type.component.ts
Labels: angular, bug

#229 [NET-884] Fix spelling error in setup script
  contrib/setup/setup.sh
Labels: bug

#230 [NET-888] Reload pagination parameter on resolve search.
  app/src/app/search/search.component.ts
Labels: bug

#231 [NET-885] Hide unused access fields
  app/src/app/framework/type/builder/configs/edits/check-field-edit.component.html
  app/src/app/framework/type/builder/configs/edits/choice-field-edit.component.html
  app/src/app/framework/type/builder/configs/edits/date-field-edit.component.html
  app/src/app/framework/type/builder/configs/edits/ref-field-edit.component.html
  app/src/app/framework/type/builder/configs/edits/section-field-edit.component.html
  app/src/app/framework/type/builder/configs/edits/text-field-edit.component.html
  app/src/app/framework/type/builder/configs/edits/textarea-edit.component.html
Labels: angular, bug

#236 [NET-901] Reverse object order of latest and newest objects
  app/src/app/framework/services/object.service.ts
Labels: angular, bug

#239 [NET- 726] Refactor aggregation workflow
  cmdb/docapi/docapi_template/docapi_template_manager.py
  cmdb/exportd/managers/exportd_job_manager.py
  cmdb/exportd/managers/exportd_log_manager.py
  cmdb/framework/managers/category_manager.py
  cmdb/framework/managers/log_manager.py
  cmdb/framework/managers/object_link_manager.py
  cmdb/framework/managers/object_manager.py
  cmdb/framework/managers/type_manager.py
  cmdb/framework/results/iteration.py
  cmdb/manager/__init__.py
  cmdb/manager/managers.py
  cmdb/user_management/managers/account_manager.py
  cmdb/user_management/managers/group_manager.py
  cmdb/user_management/managers/right_manager.py
  cmdb/user_management/managers/setting_manager.py
  cmdb/user_management/managers/user_manager.py
  cmdb/user_management/models/group.py
Labels: bug, python, refactor

#245 [NET-795] Update bootstrap 4.6.2
  app/package-lock.json
  app/package.json
  app/src/app/layout/components/feedback-form/feedback-form.component.html
Labels: dependencies, enhancement

#243 Rest data projection
  cmdb/interface/api_parameters.py
  cmdb/interface/api_project.py
  cmdb/interface/blueprint.py
  cmdb/interface/response.py
  cmdb/interface/rest_api/user_management_routes/group_parameters.py
Labels: enhancement, python

#248 [NET-886] Loading safari error object types
  app/src/app/framework/object/objects-by-type/objects-by-type.component.html
  app/src/app/framework/render/simple/date/date-simple.component.html
  app/src/app/framework/render/simple/date/date-simple.component.ts
  cmdb/framework/cmdb_object.py
  cmdb/framework/cmdb_render.py
  cmdb/framework/models/type.py
Labels: bug

#250 [NET-927] Add JwPaginationModule to search.module.ts
  app/src/app/search/search.module.ts
Labels: bug

#253 [NET-942] Separate iteration of the changes for log view.
  app/src/app/framework/object/components/object-log-list/object-log-change-view/object-log-change-view.component.html
Labels: bug

#249 [NET-896] Extend search engine for references
  app/src/app/search/search-result/search-result-bar/search-result-bar.component.html
  app/src/app/search/search-result/search-result-bar/search-result-bar.component.ts
  app/src/app/search/search-result/search-result.component.html
  app/src/app/search/search.component.html
  app/src/app/search/search.component.ts
  app/src/app/search/search.service.ts
  cmdb/interface/rest_api/search_routes.py
  cmdb/search/searchers.py
Labels: enhancement
