Repository DataGerry/DataGerry, pull requests merged in 2021-01, with the labels that each got.

#185 [NET-686] Added ACLs for object import.
  app/src/app/framework/services/type.service.ts
  app/src/app/import/import-objects/type-mapping/type-mapping.component.ts
  cmdb/framework/cmdb_object_manager.py
  cmdb/importer/importer_base.py
  cmdb/interface/rest_api/importer_routes/importer_object_routes.py
  cmdb/interface/rest_api/importer_routes/importer_route_utils.py
Labels: enhancement

#186 [NET-779] Replace object reference datatable
  app/src/app/framework/object/components/object-references-table/object-references-table.component.html
  app/src/app/framework/object/components/object-references-table/object-references-table.component.scss
  app/src/app/framework/object/components/object-references-table/object-references-table.component.ts
  app/src/app/framework/object/object-view/object-footer/object-footer.component.html
  app/src/app/framework/object/object-view/object-footer/object-reference-list/object-reference-list.component.html
  app/src/app/framework/object/object-view/object-footer/object-reference-list/object-reference-list.component.ts
  app/src/app/framework/object/object.module.ts
  app/src/app/framework/services/object.service.ts
  app/src/app/layout/helpers/type-label/type-label.component.html
  app/src/app/layout/helpers/type-label/type-label.component.ts
  cmdb/framework/managers/object_manager.py
  cmdb/interface/rest_api/framework_routes/object_routes.py
Labels: angular, enhancement, python, refactor

#189 [NET-777] Replace object links datatable
  app/src/app/framework/object/components/object-links-table/object-links-table-action-cell/object-links-table-action-cell.component.html
  app/src/app/framework/object/components/object-links-table/object-links-table-action-cell/object-links-table-action-cell.component.scss
  app/src/app/framework/object/components/object-links-table/object-links-table-action-cell/object-links-table-action-cell.component.ts
  app/src/app/framework/object/components/object-links-table/object-links-table-partner-cell/object-links-table-partner-cell.component.html
  app/src/app/framework/object/components/object-links-table/object-links-table-partner-cell/object-links-table-partner-cell.component.scss
  app/src/app/framework/object/components/object-links-table/object-links-table-partner-cell/object-links-table-partner-cell.component.ts
  app/src/app/framework/object/components/object-links-table/object-links-table.component.html
  app/src/app/framework/object/components/object-links-table/object-links-table.component.scss
  app/src/app/framework/object/components/object-links-table/object-links-table.component.ts
  app/src/app/framework/object/object-view/object-footer/object-footer.component.html
  app/src/app/framework/object/object-view/object-footer/object-links/object-links.component.html
  app/src/app/framework/object/object-view/object-footer/object-links/object-links.component.ts
  app/src/app/framework/object/object.module.ts
  app/src/app/framework/services/link.service.ts
  cmdb/framework/__init__.py
  cmdb/framework/cmdb_object_manager.py
  cmdb/framework/managers/object_link_manager.py
  cmdb/framework/models/__init__.py
  cmdb/framework/models/object_link.py
  cmdb/interface/rest_api/__init__.py
  cmdb/interface/rest_api/framework_routes/object_link_routes.py
  cmdb/interface/rest_api/framework_routes/object_routes.py
Labels: angular, enhancement, python, refactor

#177 [NET-819] Extend deprecated decorator.
  cmdb/utils/wraps.py
Labels: enhancement

#190 [NET-687] Enforce acl object logs
  app/src/app/framework/object/components/object-log-list/object-log-change-view/object-log-change-view.component.html
  app/src/app/framework/object/components/object-log-list/object-log-change-view/object-log-change-view.component.scss
  app/src/app/framework/object/components/object-log-list/object-log-change-view/object-log-change-view.component.ts
  app/src/app/framework/object/components/object-log-list/object-log-list.component.html
  app/src/app/framework/object/components/object-log-list/object-log-list.component.scss
  app/src/app/framework/object/components/object-log-list/object-log-list.component.ts
  app/src/app/framework/object/components/object-log-list/object-log-user/object-log-user.component.html
  app/src/app/framework/object/components/object-log-list/object-log-user/object-log-user.component.scss
  app/src/app/framework/object/components/object-log-list/object-log-user/object-log-user.component.ts
  app/src/app/framework/object/object-view/object-footer/object-log-list/object-log-user/object-log-user.component.ts
  app/src/app/framework/object/object.module.ts
  app/src/app/framework/services/log.service.ts
  cmdb/framework/__init__.py
  cmdb/framework/managers/log_manager.py
  cmdb/framework/models/log.py
  cmdb/interface/cmdb_app.py
  cmdb/interface/rest_api/__init__.py
  cmdb/interface/rest_api/exporter_routes/exportd_job_routes.py
  cmdb/interface/rest_api/exporter_routes/exportd_log_routes.py
  cmdb/interface/rest_api/framework_routes/object_routes.py
  cmdb/interface/rest_api/importer_routes/importer_object_routes.py
  cmdb/interface/rest_api/log_routes.py
  cmdb/security/acl/builder.py
Labels: angular, enhancement, python, typescript

#193 [NET-653] Improved Search for Public ID
  app/src/app/search/search-bar/search-bar.component.html
  app/src/app/search/search-bar/search-bar.component.ts
  app/src/app/search/search.component.html
  app/src/app/search/search.component.ts
Labels: angular, enhancement

#195 [NET-754] Object acl admin documentation
  docs/source/admin_guide/framework.rst
  docs/source/admin_guide/img/object_type_builder_acl_example.png
  docs/source/admin_guide/img/object_type_builder_acl_protected.png
  docs/source/admin_guide/img/object_type_builder_acl_setup.png
  docs/source/admin_guide/index.rst
  docs/source/admin_guide/user-management.rst
Labels: code conventions, documentation

#194 [NET-575] LDAP auth group memberships
  app/src/app/auth/services/auth.service.ts
  app/src/app/settings/auth-settings/auth-settings.component.html
  app/src/app/settings/auth-settings/auth-settings.component.ts
  app/src/app/settings/auth-settings/auth-settings.module.ts
  app/src/app/settings/auth-settings/providers/ldap-authentication-provider-form/ldap-authentication-provider-form.component.html
  app/src/app/settings/auth-settings/providers/ldap-authentication-provider-form/ldap-authentication-provider-form.component.ts
  app/src/app/settings/auth-settings/providers/ldap-authentication-provider-form/ldap-provider-form-group-mapping/ldap-provider-form-group-mapping.component.html
  app/src/app/settings/auth-settings/providers/ldap-authentication-provider-form/ldap-provider-form-group-mapping/ldap-provider-form-group-mapping.component.scss
  app/src/app/settings/auth-settings/providers/ldap-authentication-provider-form/ldap-provider-form-group-mapping/ldap-provider-form-group-mapping.component.ts
  cmdb/interface/rest_api/__init__.py
  cmdb/interface/rest_api/auth_routes.py
  cmdb/interface/rest_api/importer_routes/importer_object_routes.py
  cmdb/interface/route_utils.py
  cmdb/security/auth/__init__.py
  cmdb/security/auth/auth_errors.py
  cmdb/security/auth/auth_providers.py
  cmdb/security/auth/auth_settings.py
  cmdb/security/auth/providers/external_providers.py
  cmdb/security/auth/providers/internal_providers.py
  cmdb/security/token/generator.py
  cmdb/utils/helpers.py
  docs/source/admin_guide/authentication.rst
  docs/source/admin_guide/img/auth_provider_ldap_default.png
  docs/source/admin_guide/img/auth_provider_ldap_mapping.png
Labels: enhancement

#204 [NET-834] Added empty match query if active_only is disabled
  cmdb/interface/rest_api/framework_routes/object_routes.py
Labels: bug

#205 [NET-851] Manager insert funtkion no longer retrieves highest ID but …
  cmdb/database/managers.py
Labels: bug

#206 [NET-863] Page number doesnt reset
  app/src/app/framework/object/objects-by-type/objects-by-type.component.ts
Labels: bug

#198 [NET-590] Objects ACL manage
  app/src/app/acl/acl.module.ts
  app/src/app/acl/components/acl-objects-information-activation-column/acl-objects-information-activation-column.component.html
  app/src/app/acl/components/acl-objects-information-activation-column/acl-objects-information-activation-column.component.scss
  app/src/app/acl/components/acl-objects-information-activation-column/acl-objects-information-activation-column.component.ts
  app/src/app/acl/components/acl-objects-information-permissions-column/acl-objects-information-permissions-column.component.html
  app/src/app/acl/components/acl-objects-information-permissions-column/acl-objects-information-permissions-column.component.scss
  app/src/app/acl/components/acl-objects-information-permissions-column/acl-objects-information-permissions-column.component.ts
  app/src/app/acl/components/acl-objects-information-table/acl-objects-information-table.component.html
  app/src/app/acl/components/acl-objects-information-table/acl-objects-information-table.component.scss
  app/src/app/acl/components/acl-objects-information-table/acl-objects-information-table.component.ts
  app/src/app/framework/type/type-builder/type-builder.component.ts
  app/src/app/framework/type/type-edit/type-edit.component.html
  app/src/app/framework/type/type-edit/type-edit.component.ts
  app/src/app/layout/structure/navigation/navigation.component.html
  app/src/app/management/groups/group-acl/group-acl.component.html
  app/src/app/management/groups/group-acl/group-acl.component.scss
  app/src/app/management/groups/group-acl/group-acl.component.ts
  app/src/app/management/groups/group-edit/group-edit.component.html
  app/src/app/management/groups/group-edit/group-edit.component.ts
  app/src/app/management/groups/groups-routing.module.ts
  app/src/app/management/groups/groups.module.ts
  app/src/app/management/management-routing.module.ts
  app/src/app/management/management.component.html
  app/src/app/management/users/user-edit/user-edit.component.html
  app/src/app/management/users/user-edit/user-edit.component.ts
  app/src/app/management/users/users.module.ts
Labels: enhancement

#207 [NET-652] Export rendered filtered object results
  app/src/app/export/export-objects/export-objects.component.ts
  app/src/app/export/export-objects/model/supported-exporter-extension.ts
  app/src/app/export/export.service.ts
  app/src/app/framework/object/components/object-references-table/object-references-table.component.ts
  app/src/app/framework/object/components/object-table-head/object-table-head.component.html
  app/src/app/framework/object/components/object-table-head/object-table-head.component.ts
  app/src/app/framework/object/objects-by-type/objects-by-type.component.ts
  cmdb/exporter/config/config_base.py
  cmdb/exporter/config/config_type.py
  cmdb/exporter/exporter_base.py
  cmdb/exporter/exporter_utils.py
  cmdb/exporter/format/format_base.py
  cmdb/exporter/writer/writer_base.py
  cmdb/file_export/export_types.py
  cmdb/file_export/file_exporter.py
  cmdb/interface/rest_api/__init__.py
  cmdb/interface/rest_api/exportd_routes/__init__.py
  cmdb/interface/rest_api/exportd_routes/exportd_job_routes.py
  cmdb/interface/rest_api/exportd_routes/exportd_log_routes.py
  cmdb/interface/rest_api/exporter_routes/exporter_object_routes.py
  cmdb/interface/rest_api/exporter_routes/exporter_type_routes.py
  cmdb/interface/rest_api/exporter_routes/file_routes.py
Labels: enhancement

#212 [NET-869] Bulk changes: in-/active button trigger changes.
  app/src/app/framework/object/object-bulk-change/object-bulk-change-editor/object-bulk-change-editor.component.html
  app/src/app/framework/object/object-bulk-change/object-bulk-change-editor/object-bulk-change-editor.component.ts
  app/src/app/framework/object/object-bulk-change/object-bulk-change-preview/object-bulk-change-preview.component.html
  app/src/app/framework/object/object-bulk-change/object-bulk-change.component.ts
Labels: bug

#217 [NET-771] Remove datatables
  app/angular.json
  app/package-lock.json
  app/package.json
  app/src/app/framework/collection/collection-add/collection-add.component.html
  app/src/app/framework/collection/collection-add/collection-add.component.scss
  app/src/app/framework/collection/collection-add/collection-add.component.ts
  app/src/app/framework/collection/collection-list/collection-list.component.html
  app/src/app/framework/collection/collection-list/collection-list.component.scss
  app/src/app/framework/collection/collection-list/collection-list.component.ts
  app/src/app/framework/collection/collection-routing.module.ts
  app/src/app/framework/collection/collection-template-add/collection-template-add.component.html
  app/src/app/framework/collection/collection-template-add/collection-template-add.component.scss
  app/src/app/framework/collection/collection-template-add/collection-template-add.component.ts
  app/src/app/framework/collection/collection-template-list/collection-template-list.component.html
  app/src/app/framework/collection/collection-template-list/collection-template-list.component.scss
  app/src/app/framework/collection/collection-template-list/collection-template-list.component.ts
  app/src/app/framework/collection/collection.component.html
  app/src/app/framework/collection/collection.component.scss
  app/src/app/framework/collection/collection.component.ts
  app/src/app/framework/collection/collection.module.ts
  app/src/app/framework/framework-routing.module.ts
  app/src/app/framework/models/cmdb-datatable.ts
  app/src/app/framework/object/object.module.ts
  app/src/app/framework/object/user-object/user-object-changed/user-object-changed.component.html
  app/src/app/framework/object/user-object/user-object-changed/user-object-changed.component.scss
  app/src/app/framework/object/user-object/user-object-changed/user-object-changed.component.ts
  app/src/app/framework/object/user-object/user-object-routing.module.ts
  app/src/app/framework/object/user-object/user-object.module.ts
  app/src/app/framework/object/user-object/user-objects-new/user-objects-new.component.html
  app/src/app/framework/object/user-object/user-objects-new/user-objects-new.component.scss
  app/src/app/framework/object/user-object/user-objects-new/user-objects-new.component.ts
  app/src/app/framework/object/user-object/your-objects/your-objects.component.html
  app/src/app/framework/object/user-object/your-objects/your-objects.component.scss
  app/src/app/framework/object/user-object/your-objects/your-objects.component.ts
  app/src/app/framework/services/object.service.ts
  app/src/app/import/import.module.ts
  app/src/app/layout/layout.module.ts
  app/src/app/management/users/users.module.ts
  app/src/app/search/search.module.ts
  app/src/scss/_table.scss
  app/src/styles.scss
Labels: angular, dependencies, enhancement, refactor
