Repository DataGerry/DataGerry, pull requests merged in 2021-04, with the labels that each got.

#294 [NET-981] Fix doc api render error on downloading pdf file routes
  cmdb/docapi/docapi_base.py
  cmdb/interface/rest_api/importer_routes/importer_object_routes.py
  cmdb/templates/template_data.py
Labels: bug

#292 [NET-979] Fix loading table items order error on right list
  app/src/app/management/rights/rights.component.html
  app/src/app/management/rights/rights.component.ts
Labels: bug

#293 [NET-980] Fix using the item instead of the data in users-list for date display
  app/src/app/management/users/users.component.html
Labels: bug

#295 [NET-957] Reference display sections
  app/src/app/framework/object/components/object-references/object-references-by-type/object-references-by-type.component.html
  app/src/app/framework/object/components/object-references/object-references-by-type/object-references-by-type.component.ts
  app/src/app/framework/object/components/object-references/object-references-table/object-references-table.component.html
  app/src/app/framework/object/components/object-references/object-references-table/object-references-table.component.ts
  app/src/app/framework/object/components/object-references/object-references-type-column/object-references-type-column.component.html
  app/src/app/framework/object/components/object-references/object-references-type-column/object-references-type-column.component.scss
  app/src/app/framework/object/components/object-references/object-references-type-column/object-references-type-column.component.ts
  app/src/app/framework/object/object.module.ts
  cmdb/framework/managers/object_manager.py
  cmdb/search/query/builder.py
Labels: enhancement

#297 [NET-986] Complete objects list
  app/src/app/framework/object/object-routing.module.ts
  app/src/app/framework/object/object.component.html
  app/src/app/framework/object/object.component.scss
  app/src/app/framework/object/object.component.ts
  app/src/app/framework/object/object.module.ts
  cmdb/framework/managers/object_manager.py
Labels: enhancement

#298 [NET-987] Nullpointer when displaying changes in the object log list
  app/src/app/framework/object/components/object-log-list/object-log-change-view/object-log-change-view.component.ts
Labels: bug

#299 [NET-988] Fix field not found error handling in object render
  cmdb/framework/cmdb_render.py
Labels: bug

#301 [NET-1001] Center active column in dashboard tables
  app/src/app/dashboard/dashboard.component.html
Labels: bug

#303 [NET-1010] Update dependabot.yml
  .github/dependabot.yml
Labels: dependencies

#302 [NET-954] Searchable reference section
  app/src/app/search/search-bar/search-bar-tag-settings-form/search-bar-tag-settings-form.component.ts
  app/src/app/search/search-bar/search-bar-tag/search-bar-tag-icon.component.ts
  app/src/app/search/search-bar/search-bar-tag/search-bar-tag.component.ts
  app/src/app/search/search-result/search-result-bar/search-result-bar.component.html
  app/src/app/search/search-result/search-result-bar/search-result-bar.component.ts
  app/src/app/search/search.component.html
  app/src/app/search/search.component.ts
  cmdb/framework/cmdb_render.py
  cmdb/interface/rest_api/search_routes.py
  cmdb/search/search_result.py
  cmdb/search/searchers.py
Labels: enhancement

#304 [NET-1004] Set correct timestamp for last-edit.
  cmdb/importer/importer_base.py
Labels: bug

#305 [NET-974 ] Exportd regex condition and limited transfer
  app/src/app/exportd/exportd-job-settings-builder/exportd-job-scheduling-step/exportd-job-scheduling-step.component.html
  app/src/app/exportd/exportd-job-settings-builder/exportd-job-scheduling-step/exportd-job-scheduling-step.component.ts
  cmdb/exportd/exportd_job/exportd_job.py
  cmdb/exportd/exportd_job/exportd_job_manager.py
  cmdb/exportd/exporter_base.py
  cmdb/exportd/externals/external_systems.py
  cmdb/exportd/service.py
  cmdb/framework/cmdb_object_manager.py
  cmdb/interface/rest_api/exportd_routes/exportd_job_routes.py
  cmdb/templates/template_data.py
Labels: enhancement

#308 [NET-1021] Show uncategorised and deactivated types in sidebar.
  app/src/app/framework/services/type.service.ts
  app/src/app/layout/structure/sidebar/sidebar.component.ts
Labels: bug

#306 [NET-1012] Correction of the resolution of summary fields.
  app/src/app/search/search-result/search-result-bar/search-result-bar.component.ts
  cmdb/framework/cmdb_render.py
  cmdb/search/search_result.py
Labels: bug

#311 [NET-1022] Change from datetime.now() to datetime.now(timezone.utc)
  cmdb/__setup__.py
  cmdb/docapi/docapi_template/docapi_template_manager.py
  cmdb/exportd/exportd_job/exportd_job_manager.py
  cmdb/exportd/exportd_logs/exportd_log_manager.py
  cmdb/exportd/service.py
  cmdb/framework/cmdb_object_manager.py
  cmdb/framework/cmdb_render.py
  cmdb/framework/managers/log_manager.py
  cmdb/framework/managers/object_link_manager.py
  cmdb/framework/models/link.py
  cmdb/framework/models/type.py
  cmdb/importer/importer_base.py
  cmdb/importer/importer_object.py
  cmdb/interface/response.py
  cmdb/interface/rest_api/auth_routes.py
  cmdb/interface/rest_api/exportd_routes/exportd_job_routes.py
  cmdb/interface/rest_api/framework_routes/category_routes.py
  cmdb/interface/rest_api/framework_routes/object_routes.py
  cmdb/interface/rest_api/framework_routes/type_routes.py
  cmdb/interface/rest_api/importer_routes/importer_type_routes.py
  cmdb/interface/rest_api/user_management_routes/user_routes.py
  cmdb/media_library/media_file_manager.py
  cmdb/security/auth/providers/external_providers.py
  cmdb/security/token/generator.py
  cmdb/user_management/models/user.py
Labels: python

#310 Update AUTHORS.md
  AUTHORS.md
Labels: refactor

#307 [NET-1006] Types extended by properties editor_id and last_edit_time.
  app/src/app/framework/models/cmdb-type.ts
  app/src/app/framework/type/type-builder/type-builder.component.ts
  app/src/app/framework/type/type-delete/type-delete.component.ts
  app/src/app/framework/type/type.component.html
  app/src/app/framework/type/type.component.ts
  app/src/app/framework/type/type.module.ts
  cmdb/framework/models/type.py
  cmdb/interface/rest_api/framework_routes/type_routes.py
Labels: enhancement

#312 [NET-1023] Skip pagination reset.
  app/src/app/search/search.component.ts
Labels: bug

#313 [NET-1024] Fix removeField function uses item.name instead of item
  app/src/app/framework/type/builder/builder.component.ts
Labels: angular, bug

#314 [NET-1025] Show references with summaries.
  app/src/app/framework/render/fields/special/ref.component.html
  app/src/app/framework/render/fields/special/ref.component.ts
  cmdb/framework/cmdb_render.py
  cmdb/framework/models/type.py
Labels: bug
