Repository DataGerry/DataGerry, pull requests merged in 2021-05, with the labels that each got.

#321 [NET-1028] Default-value are not setting automatic on create object
  app/src/app/framework/render/render.component.ts
  app/src/app/framework/render/sections/base-section/base-section.component.ts
  app/src/app/framework/render/sections/reference-section/reference-section.component.ts
Labels: bug

#320 [NET-794] Update crypto packages
  .github/workflows/continous-integration.yml
  requirements.txt
Labels: dependencies

#318 [NET-1016] Documentation rest object routes into development
  app/src/app/framework/services/object.service.ts
  cmdb/interface/rest_api/__init__.py
  cmdb/interface/rest_api/framework_routes/object_routes.py
  docs/source/api/rest/framework.rst
Labels: documentation

#328 [NET-1061] Load predefined option at typegenerator.
  app/src/app/framework/type/builder/configs/choice/choice-field-edit.component.html
  app/src/app/framework/type/builder/configs/choice/choice-field-edit.component.ts
Labels: bug

#330 [NET-1060] Crash after change type without cleanup
  cmdb/framework/cmdb_render.py
  cmdb/templates/template_data.py
Labels: bug

#331 [NET-1062] Update blueprints for object routes.
  app/src/app/framework/services/object.service.ts
  app/src/app/services/api-call.service.ts
  cmdb/interface/rest_api/__init__.py
  cmdb/interface/rest_api/framework_routes/object_routes.py
  cmdb/templates/template_data.py
Labels: bug

#333 [NET-1063] Resolve Reference-Fields at the Doc-API.
  app/src/app/framework/render/fields/section/ref-section.component.html
  app/src/app/framework/type/builder/configs/section/section-ref-field-edit.component.ts
  app/src/app/services/api-call.service.ts
  cmdb/framework/cmdb_render.py
  cmdb/templates/template_data.py
Labels: bug

#334 [NET-1064] Resolve reference-section-fields during bulk change.
  app/src/app/framework/object/object-bulk-change/object-bulk-change-preview/object-bulk-change-preview.component.html
  app/src/app/framework/object/object-bulk-change/object-bulk-change.component.scss
  app/src/app/framework/render/components/input-appends/input-appends.component.html
  app/src/app/framework/render/components/object-bulk-input-appends/object-bulk-input-appends.component.html
  app/src/app/framework/render/fields/choice/checkbox.component.html
  app/src/app/framework/render/fields/choice/radio.component.html
  app/src/app/framework/render/fields/section/ref-section.component.html
  app/src/app/framework/render/fields/section/ref-section.component.scss
  app/src/app/framework/render/fields/section/ref-section.component.ts
  app/src/app/framework/render/fields/special/ref.component.html
  app/src/app/framework/render/fields/special/ref.component.scss
  app/src/app/framework/render/simple/date/date-simple.component.html
  app/src/app/framework/render/simple/date/date-simple.component.ts
  app/src/app/framework/render/simple/special/ref-section-simple.component.html
  app/src/app/layout/pipes/date-formatter.pipe.ts
  cmdb/framework/cmdb_render.py
Labels: bug

#335 [NET-1065] Default values are not set
  app/src/app/framework/render/components/input-appends/input-appends.component.html
  app/src/app/framework/render/sections/base-section/base-section.component.ts
Labels: bug

#336 [NET-1014] Extension of the documentation for exporting objects
  docs/source/admin_guide/framework.rst
  docs/source/admin_guide/img/object-import-export.png
  docs/source/admin_guide/img/raw-custom-export.png
Labels: documentation

#337 [NET-1020] Extension of the documentation for exportd.
  cmdb/exportd/exportd_job/exportd_job_manager.py
  docs/source/admin_guide/exportd.rst
  docs/source/admin_guide/framework.rst
Labels: documentation

#339 [NET-1066] Load number of objects when opening the category points.
  app/src/app/dashboard/dashboard.component.ts
  app/src/app/layout/services/sidebar.service.ts
  app/src/app/layout/structure/sidebar/sidebar-category.component.html
  app/src/app/layout/structure/sidebar/sidebar-category.component.ts
  app/src/app/layout/structure/sidebar/sidebar-type.component.ts
Labels: enhancement

#340 [NET-940] Object reference field values made searchable.
  app/src/app/framework/object/components/object-references/object-references-by-type/object-references-by-type.component.html
  app/src/app/framework/object/components/object-references/object-references-by-type/object-references-by-type.component.ts
  app/src/app/framework/object/components/object-references/object-references-table/object-references-table.component.html
  app/src/app/framework/object/components/object-references/object-references-table/object-references-table.component.ts
  app/src/app/framework/object/objects-by-type/objects-by-type.component.ts
Labels: bug, enhancement

#342 [NET-1067] Filter over reference field values at the object list.
  app/src/app/framework/object/object.component.ts
Labels: enhancement

#343 [NET-1068] Admin Guide: Object table filter.
  docs/source/admin_guide/framework.rst
Labels: documentation
